version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mnist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:pg
    restart: unless-stopped

  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mnist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
