version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mnist-database  # Named container
    environment:
      POSTGRES_USER: postgres      # Admin username
      POSTGRES_PASSWORD: postgres  # Admin password
      POSTGRES_DB: mnist           # Database name (auto-created on startup)
      POSTGRES_HOST_AUTH_METHOD: trust  # Explicit authentication method
    volumes:
      # Persistent data storage
      - postgres_data:/var/lib/postgresql/data  
      # SQL script that creates tables (runs ONLY on first initialization)
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mnist"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    networks:
      - app-network

  app:
    build: .
    container_name: mnist-app  # Named container
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mnist
    networks:
      - app-network

volumes:
  postgres_data:  # Named volume for persistent storage

networks:
  app-network:
    driver: bridge
